CREATE SEQUENCE "SCHEDULER_TEST_SEQ"
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

CREATE TABLE  SCHEDULER_TEST(
  ID int  PRIMARY KEY,
  NAME varchar(100) ,
  COMMENTS varchar(100) );

